import { useState, type CSSProperties, type FormEvent } from "react";
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, Flame, Pencil, PlayCircle, Plus, Target, Trash2 } from "lucide-react";
import { useData } from "../hooks/useData";
import { PageHeader, DashboardCard, Modal, ConfirmDialog, ProgressBar, ProgressRing } from "../components/ui";
import type { LectureLog, LecturePlan, LectureWorkspace } from "../types";
import { addDays, dateKey, number, prettyDate, uid } from "../utils/date";
import { buildLectureCSV, emptyLectures, lectureDays, lectureStats } from "../utils/lectures";
import { download, exportJSON } from "../services/export";

export default function Lectures() {
  const { data, saveLectures } = useData();
  const w = data.lectures || emptyLectures();
  const [date, setDate] = useState(dateKey), [subject, setSubject] = useState(""), [span, setSpan] = useState(14), [history, setHistory] = useState(false);
  const [plan, setPlan] = useState<LecturePlan | "new">(), [entry, setEntry] = useState<{ planId?: string; log?: LectureLog }>();
  const [deleting, setDeleting] = useState<LectureLog>();
  const stats = lectureStats(w, date, subject), days = lectureDays(w, date, span, subject), heatmap = lectureDays(w, date, 28, subject);
  const daily = stats.logs.filter(l => history || l.date === date).sort((a, b) => b.date.localeCompare(a.date) || a.planId.localeCompare(b.planId));
  const max = Math.max(1, ...days.map(d => d.completed));
  const name = (subjectId: string) => data.subjects.find(s => s.id === subjectId)?.name || "Subject";
  return <div className="lecture-workspace">
    <PageHeader eyebrow="WORKSPACE · LECTURE PLANNER" title="Lectures" description="Set a subject target. Log each day's completed lectures. See your progress build." action={<div className="lecture-actions"><button className="btn secondary" onClick={() => setPlan("new")} disabled={w.plans.length >= data.subjects.length}><Target size={17} />Set lecture target</button><button className="btn primary" disabled={!w.plans.length} onClick={() => setEntry({})}><Plus size={17} />Log lectures</button></div>} />
    <div className="lecture-toolbar"><div className="date-navigation"><button className="icon-btn" aria-label="Previous lecture day" onClick={() => setDate(addDays(date, -1))}><ChevronLeft size={18} /></button><input type="date" aria-label="Lecture overview date" value={date} max={dateKey()} onChange={e => { if (e.target.value && e.target.value <= dateKey()) setDate(e.target.value); }} /><button className="icon-btn" aria-label="Next lecture day" disabled={date >= dateKey()} onClick={() => setDate(addDays(date, 1))}><ChevronRight size={18} /></button><button className="text-btn" onClick={() => setDate(dateKey())}>Today</button></div><label className="lecture-filter">Subject<select aria-label="Lecture subject filter" value={subject} onChange={e => setSubject(e.target.value)}><option value="">All subjects</option>{w.plans.map(p => <option value={p.subjectId} key={p.id}>{name(p.subjectId)}</option>)}</select></label></div>
    <div className="stats-grid four lecture-kpis"><DashboardCard title="Total target" value={number(stats.target)} detail={`${stats.subjects.length} subjects planned`} icon={<Target size={18} />} /><DashboardCard title="Completed" value={number(stats.completed)} detail={`Through ${prettyDate(date)}`} tone="green" icon={<CheckCircle2 size={18} />} /><DashboardCard title="Remaining" value={number(stats.remaining)} detail="Across your subject targets" tone="amber" icon={<PlayCircle size={18} />} /><DashboardCard title="Completed this day" value={number(stats.today)} detail={`${stats.weekly} in the week so far`} tone="purple" icon={<CalendarDays size={18} />} /></div>
    <div className="lecture-overview-grid"><section className="card lecture-overall"><div className="lecture-section-title"><div><span className="eyebrow">YOUR BIG PICTURE</span><h2>Overall completion</h2></div><span className="badge blue">{prettyDate(date)}</span></div><div className="lecture-ring-area"><ProgressRing value={stats.progress} size={144} label={`${Math.round(stats.progress)}% of subject lecture targets complete`} /><div><strong>{Math.round(stats.progress)}% complete</strong><p>{w.plans.length ? "A little progress each day adds up." : "Start with one subject and set a realistic target."}</p><span className="small muted">Extra lectures in one subject keep other subjects' targets unchanged.</span></div></div><div className="lecture-mini-stats"><div><Flame size={18} /><strong>{stats.streak}</strong><span>day streak</span></div><div><Clock3 size={18} /><strong>{number(stats.minutes / 60)}h</strong><span>time logged</span></div><div><CheckCircle2 size={18} /><strong>{stats.activeDays}</strong><span>active days</span></div></div></section>
    <section className="card lecture-chart"><div className="lecture-section-title"><div><span className="eyebrow">SHOW UP, EVERY DAY</span><h2>Daily completions</h2></div><select aria-label="Lecture chart period" value={span} onChange={e => setSpan(Number(e.target.value))}><option value={7}>7 days</option><option value={14}>14 days</option><option value={28}>28 days</option></select></div><p className="small muted">{days.reduce((n, d) => n + d.completed, 0)} lectures in this period · select a day to view its log</p><div className="lecture-bars" style={{ "--days": span } as CSSProperties} aria-label="Daily completed lecture chart">{days.map((d, i) => <button key={d.date} className={d.date === date ? "selected" : ""} aria-label={`${prettyDate(d.date)}: ${d.completed} lectures`} title={`${prettyDate(d.date)} · ${d.completed} lectures`} onClick={() => { setDate(d.date); setHistory(false); }}><span className="lecture-bar-value">{d.completed || ""}</span><span className="lecture-bar-track"><span style={{ height: `${d.completed ? Math.max(5, 100 * d.completed / max) : 3}%` }} /></span><small>{span <= 14 || i % 4 === 0 || i === days.length - 1 ? prettyDate(d.date, { day: "numeric" }) : ""}</small></button>)}</div></section></div>
    <div className="lecture-section-title"><div><span className="eyebrow">ONE SUBJECT AT A TIME</span><h2>Subject targets</h2></div><button className="text-btn" disabled={w.plans.length >= data.subjects.length} onClick={() => setPlan("new")}><Plus size={16} />Add target</button></div>
    {!stats.subjects.length ? <section className="card lecture-empty"><div className="lecture-empty-icon"><PlayCircle size={32} /></div><h3>Your first lecture target starts here.</h3><p>Choose a subject, add the number of lectures you want to finish, and log your daily progress.</p><button className="btn primary" onClick={() => setPlan("new")}><Plus size={16} />Set your first target</button></section> : <div className="lecture-target-grid">{stats.subjects.map(p => { const s = data.subjects.find(s => s.id === p.subjectId)!; return <article className="card lecture-subject-card" key={p.id} style={{ "--subject-color": s.color } as CSSProperties}><div className="lecture-subject-head"><span className="lecture-subject-icon"><PlayCircle size={21} /></span><div><h3>{s.name}</h3><p>{p.course || "Subject lectures"}</p></div><button className="icon-btn" aria-label={`Edit ${s.name} target`} onClick={() => setPlan(p)}><Pencil size={16} /></button></div><div className="lecture-subject-count"><strong>{p.completed}<span> / {p.target}</span></strong><span className={`badge ${p.remaining ? "blue" : "green"}`}>{p.remaining ? `${Math.round(p.progress)}%` : "Target complete"}</span></div><ProgressBar value={p.progress} label={`${s.name} completion`} detail={`${p.remaining} remaining`} /><div className="lecture-subject-meta"><span><CalendarDays size={14} />{p.dailyTarget ? `${p.today}/${p.dailyTarget} on ${prettyDate(date)}` : "Daily target optional"}</span><span>{p.dueDate ? `Due ${prettyDate(p.dueDate)}` : "No deadline"}</span></div>{p.completed > p.target && <p className="small lecture-extra">{p.completed - p.target} extra lectures completed</p>}{p.dueDate && p.remaining > 0 && <p className="small muted">{p.neededPerDay === null ? "Deadline passed · update your target date" : `${p.neededPerDay} per day needed to meet your deadline`}</p>}<button className="btn secondary" aria-label={`Log ${s.name} lectures`} onClick={() => setEntry({ planId: p.id })}><Plus size={16} />Log daily progress</button></article>; })}</div>}
    <div className="lecture-bottom-grid"><section className="card lecture-log-card"><div className="lecture-section-title"><div><span className="eyebrow">YOUR DAILY RECORD</span><h2>{history ? "Completion history" : `Log for ${prettyDate(date)}`}</h2></div><button className="text-btn" onClick={() => setHistory(!history)}>{history ? "Selected day" : "All history"}</button></div>{!daily.length && <div className="lecture-log-empty"><CalendarDays size={25} /><p>No lectures recorded {history ? "yet" : "for this day"}.</p><button className="text-btn" disabled={!w.plans.length} onClick={() => setEntry({})}>Log your progress</button></div>}{daily.map(l => { const p = w.plans.find(p => p.id === l.planId)!; return <div className="lecture-log-row" key={l.id}><div className="lecture-log-date"><strong>{prettyDate(l.date, { day: "numeric" })}</strong><small>{prettyDate(l.date, { month: "short" })}</small></div><div className="lecture-log-content"><strong>{name(p.subjectId)}</strong><p>{p.course || "Subject lectures"}{l.minutes ? ` · ${l.minutes} min` : ""}</p>{l.notes && <p className="small muted">{l.notes}</p>}</div><span className="lecture-log-count">+{l.completed}<small>lectures</small></span><button className="icon-btn" aria-label={`Edit ${name(p.subjectId)} log ${l.date}`} onClick={() => setEntry({ log: l })}><Pencil size={16} /></button><button className="icon-btn" aria-label={`Delete ${name(p.subjectId)} log ${l.date}`} onClick={() => setDeleting(l)}><Trash2 size={16} /></button></div>; })}</section><section className="card lecture-consistency"><div className="lecture-section-title"><div><span className="eyebrow">KEEP THE MOMENTUM</span><h2>28-day activity</h2></div><Flame size={20} /></div><div className="lecture-heatmap">{heatmap.map(d => <button key={d.date} className={`level-${d.completed ? d.completed >= 5 ? 3 : d.completed >= 3 ? 2 : 1 : 0} ${d.date === date ? "selected" : ""}`} aria-label={`Activity ${d.date}: ${d.completed} lectures`} title={`${prettyDate(d.date)} · ${d.completed} lectures`} onClick={() => { setDate(d.date); setHistory(false); }}>{prettyDate(d.date, { day: "numeric" })}</button>)}</div><div className="lecture-heatmap-legend"><span>Fewer</span><i className="level-0" /><i className="level-1" /><i className="level-2" /><i className="level-3" /><span>More</span></div><p className="small muted">{heatmap.filter(d => d.completed > 0).length} active days out of 28. Each square opens that day's log.</p><div className="lecture-export"><button className="btn secondary" onClick={() => download(buildLectureCSV(data), `upsc-lectures-${dateKey()}.csv`, "text/csv;charset=utf-8;")}><Download size={16} />Export lecture CSV</button><button className="text-btn" onClick={() => exportJSON(data)}>Back up workspace</button></div></section></div>
    {plan && <TargetForm plan={plan === "new" ? undefined : plan} workspace={w} close={() => setPlan(undefined)} />}
    {entry && <LogForm workspace={w} date={date} planId={entry.planId} log={entry.log} close={() => setEntry(undefined)} />}
    {deleting && <ConfirmDialog title="Delete this day's lecture entry?" text="This removes this entry from your lecture totals. Other days and your subject target stay saved." label="Delete entry" danger onClose={() => setDeleting(undefined)} onConfirm={() => saveLectures({ ...w, logs: w.logs.filter(l => l.id !== deleting.id) })} />}
  </div>;
}
function TargetForm({ plan, workspace: w, close }: { plan?: LecturePlan; workspace: LectureWorkspace; close: () => void }) {
  const { data, saveLectures } = useData();
  const available = data.subjects.filter(s => plan?.subjectId === s.id || !w.plans.some(p => p.subjectId === s.id));
  const [form, setForm] = useState<LecturePlan>(plan || { id: uid(), subjectId: available[0]?.id || "", course: "", target: 40, dailyTarget: 2, dueDate: "" });
  const submit = (e: FormEvent) => { e.preventDefault(); const next = { ...form, course: form.course.trim() }; if (saveLectures({ ...w, plans: [...w.plans.filter(p => p.id !== next.id), next] })) close(); };
  return <Modal title={plan ? "Edit lecture target" : "Set lecture target"} onClose={close}><form onSubmit={submit}><div className="modal-body"><p className="lecture-form-intro">Set the total lectures you aim to finish in this subject. You can change the target as your course grows.</p><div className="form-grid"><label>Subject<select aria-label="Target lecture subject" value={form.subjectId} disabled={!!plan} onChange={e => setForm({ ...form, subjectId: e.target.value })}>{available.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Total lecture target<input aria-label="Total lecture target" type="number" min={1} max={10000} step={1} required value={form.target} onChange={e => setForm({ ...form, target: Number(e.target.value) })} /></label><label>Daily target (optional)<input aria-label="Daily lecture target" type="number" min={0} max={100} step={1} required value={form.dailyTarget} onChange={e => setForm({ ...form, dailyTarget: Number(e.target.value) })} /></label><label>Finish by (optional)<input aria-label="Lecture target deadline" type="date" value={form.dueDate} onChange={e => setForm({ ...form, dueDate: e.target.value })} /></label><label className="span-2">Course or teacher (optional)<input aria-label="Lecture course" maxLength={200} value={form.course} placeholder="e.g. Foundation course · Indian polity" onChange={e => setForm({ ...form, course: e.target.value })} /></label></div></div><div className="modal-foot"><button className="btn secondary" type="button" onClick={close}>Cancel</button><button className="btn primary" type="submit">Save target</button></div></form></Modal>;
}
function LogForm({ workspace: w, date, planId, log, close }: { workspace: LectureWorkspace; date: string; planId?: string; log?: LectureLog; close: () => void }) {
  const { data, saveLectures } = useData();
  const selected = planId || log?.planId || w.plans[0]?.id || "";
  const existing = log || w.logs.find(l => l.planId === selected && l.date === date);
  const fresh = (id: string, day: string): LectureLog => w.logs.find(l => l.planId === id && l.date === day) || { id: uid(), planId: id, date: day, completed: 1, minutes: 0, notes: "" };
  const [form, setForm] = useState(existing || fresh(selected, date));
  const submit = (e: FormEvent) => { e.preventDefault(); if (saveLectures({ ...w, logs: [...w.logs.filter(l => l.id !== form.id && !(l.planId === form.planId && l.date === form.date)), form] })) close(); };
  return <Modal title="Log completed lectures" onClose={close}><form onSubmit={submit}><div className="modal-body"><p className="lecture-form-intro">Enter the total completed for this subject on this date. Saving updates the day's entry and keeps other days unchanged.</p><div className="form-grid"><label>Subject<select aria-label="Log lecture subject" value={form.planId} disabled={!!log} onChange={e => setForm(fresh(e.target.value, form.date))}>{w.plans.map(p => <option value={p.id} key={p.id}>{data.subjects.find(s => s.id === p.subjectId)?.name}</option>)}</select></label><label>Date<input aria-label="Lecture completion date" type="date" required max={dateKey()} disabled={!!log} value={form.date} onChange={e => { if (e.target.value) setForm(fresh(form.planId, e.target.value)); }} /></label><label>Lectures completed<input aria-label="Lectures completed" type="number" min={1} max={1000} step={1} required value={form.completed} onChange={e => setForm({ ...form, completed: Number(e.target.value) })} /></label><label>Time spent in minutes (optional)<input aria-label="Lecture minutes" type="number" min={0} max={1440} step={1} value={form.minutes} onChange={e => setForm({ ...form, minutes: Number(e.target.value) })} /></label><label className="span-2">Notes (optional)<textarea aria-label="Lecture notes" maxLength={10000} value={form.notes} placeholder="Topics covered, lecture numbers, or what to revise…" onChange={e => setForm({ ...form, notes: e.target.value })} /></label></div>{w.logs.some(l => l.planId === form.planId && l.date === form.date) && <p className="small muted lecture-form-hint">A saved entry exists for this day. You are editing its total.</p>}</div><div className="modal-foot"><button className="btn secondary" type="button" onClick={close}>Cancel</button><button className="btn primary" type="submit">Save daily progress</button></div></form></Modal>;
}
