export type MockPaper = "GS-I" | "CSAT";
export type MockQuestion = {id:string;question:string;options:Record<string,string>;correct?:string;explanation?:string;subject:string;topic:string;subtopic?:string;difficulty:string;positive:number;negative:number;blocks?:{type:string;text?:string;items?:string[];headers?:string[];rows?:string[][]}[];response?:MockResponse;outcome?:string;net?:number};
export type MockResponse = {option:string;review:boolean;visited:boolean;seconds:number;confidence:string;strategy:string;note?:string;errorType?:string;bookmarked?:boolean;revisionDate?:string;firstSeen?:number;answeredAt?:number};
export type MockTest = {id:string;code:string;name:string;coachingId:string|null;coaching:string;series:string;year:number;paper:MockPaper;kind:string;subjects:string[];topics:string[];syllabus:string;difficulty:string;duration:number;positive:number;negative:number;question_count:number;maximum:number;participants:number;started:number;attempt_limit:number;status:string;scheduled_at?:string;closes_at?:string;language:string;leaderboard:boolean};
export type Position={display_name:string;rank:number;score:number;accuracy:number;incorrect:number;seconds:number;attempted:number;percentile:number};
export type MockResult={questions:MockQuestion[];count:number;attempted:number;correct:number;incorrect:number;unattempted:number;gross:number;negative:number;score:number;maximum:number;accuracy:number;attemptRate:number;seconds:number};
export type MockAttempt={id:string;testId:string|null;test:MockTest;mode:string;eligible:boolean;status:string;startedAt:string;deadline:string;submittedAt?:string;serverNow:string;answers:Record<string,MockResponse>;index:number;sequence:number;questions:MockQuestion[];result?:MockResult;position?:Position;community?:{participants:number;mean?:number;median?:number;highest?:number;accuracy?:number;seconds?:number;top25Median?:number;top10Median?:number;histogram?:{name:string;low:number;high:number;value:number}[];curve?:{score:number;percentile:number}[];sample?:{score:number;accuracy:number;seconds:number;attempted:number;mine:boolean}[]};questionCommunity?:Record<string,Record<string,number>>};
export type MockHistory=Omit<MockAttempt,"questions"|"answers"|"result"> & {result?:Omit<MockResult,"questions">};
export const mockKinds=["Sectional","Full Length","Topic Test","Revision Test","Current Affairs Test","PYQ Simulation"];
export const mockErrors=["Concept Gap","Fact Forgotten","Confused Options","Overthinking","Poor Elimination","Guessing","Question Misread","Current Affairs Gap","Silly Mistake","Time Pressure"];
export const reverseInstituteDisplayName=(name:string)=>name.trim().replace(/[\p{L}\p{N}'’]+/gu,word=>Array.from(word).reverse().join(""));
export const newMockResponse=():MockResponse=>({option:"",review:false,visited:false,seconds:0,confidence:"",strategy:""});
export const fmtMock=(value:number|undefined,unit="")=>value==null?"—":`${Number(value.toFixed(2))}${unit}`;
export const mockTime=(seconds:number)=>`${Math.floor(Math.max(0,seconds)/60)}:${String(Math.floor(Math.max(0,seconds))%60).padStart(2,"0")}`;
export function groupMockQuestions(qs:MockQuestion[],key:"subject"|"topic"|"errorType"|"confidence"|"strategy"|"difficulty"){
 const groups=new Map<string,{name:string;questions:number;attempted:number;correct:number;incorrect:number;net:number;negative:number;seconds:number;accuracy:number;attemptRate:number;scorePercent:number}>();
 for(const q of qs){const name=(key==="errorType"||key==="confidence"||key==="strategy"?q.response?.[key]:q[key])||"Not tagged";const r=groups.get(name)||{name,questions:0,attempted:0,correct:0,incorrect:0,net:0,negative:0,seconds:0,accuracy:0,attemptRate:0,scorePercent:0};r.questions++;r.attempted+=q.outcome!=="Unattempted"?1:0;r.correct+=q.outcome==="Correct"?1:0;r.incorrect+=q.outcome==="Incorrect"?1:0;r.net+=q.net||0;r.negative+=q.outcome==="Incorrect"?q.negative:0;r.seconds+=q.response?.seconds||0;groups.set(name,r);}
 return [...groups.values()].map(g=>({...g,accuracy:g.attempted?100*g.correct/g.attempted:0,attemptRate:100*g.attempted/g.questions,scorePercent:100*g.net/qs.filter(q=>((key==="errorType"||key==="confidence"||key==="strategy"?q.response?.[key]:q[key])||"Not tagged")===g.name).reduce((s,q)=>s+q.positive,0)||0}));
}
export function mockInsights(qs:MockQuestion[],target=75){return groupMockQuestions(qs,"topic").filter(g=>g.attempted>0&&(g.accuracy<target||g.incorrect>0)).sort((a,b)=>b.negative-a.negative||a.accuracy-b.accuracy).slice(0,5).map(g=>({...g,action:`Review ${g.name}: ${g.incorrect} errors across ${g.attempted} attempted questions; ${fmtMock(g.accuracy,"%")} accuracy. Revise the explanations, then practise related PYQs.`}));}
export function parseMockCSV(text:string):Record<string,string>[] {
 const rows:string[][]=[];let row:string[]=[],field="",quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===","&&!quoted){row.push(field);field="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field="";}else field+=c;}
 if(quoted)throw Error("Unclosed quoted CSV field");row.push(field);if(row.some(v=>v.trim()))rows.push(row);const headers=rows.shift()?.map(h=>h.trim().toLowerCase().replace(/[ _-]/g,""))||[];
 if(new Set(headers).size!==headers.length)throw Error("Repeated CSV headers");return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]||""])));
}
export function importMockQuestions(text:string):Omit<MockQuestion,"id">[]{
 let rows:Record<string,any>[];
 if(text.trim().startsWith("[")||text.trim().startsWith("{")){const data=JSON.parse(text);rows=Array.isArray(data)?data:data.questions;}else rows=parseMockCSV(text);
 if(!Array.isArray(rows)||!rows.length||rows.length>250)throw Error("Provide 1–250 questions in JSON or CSV");
 const seen=new Set<string>();return rows.map((row,i)=>{const value=(...keys:string[])=>keys.map(k=>row[k]).find(v=>v!==undefined&&v!=="");const options:Record<string,string>=row.options||Object.fromEntries(["a","b","c","d","e"].map(k=>[k,String(value(`option${k}`,`option ${k.toUpperCase()}`)||"")]).filter(([,v])=>v));
 const question=String(value("question","Question")||"").trim(),correct=String(value("correct","correctanswer","answer")||"").toLowerCase(),explanation=String(value("explanation","Explanation")||"").trim(),subject=String(value("subject","Subject")||"").trim(),topic=String(value("topic","Topic")||"").trim();
 if(question.length<8||![4,5].includes(Object.keys(options).length)||!options[correct]||explanation.length<8||!subject||!topic||new Set(Object.values(options).map(v=>v.trim().toLowerCase())).size!==Object.keys(options).length)throw Error(`Question ${i+1}: supply a complete question, distinct choices, correct answer, explanation, subject and topic`);
 const fingerprint=question.toLowerCase().replace(/\s+/g," ")+JSON.stringify(Object.values(options).map(v=>v.toLowerCase().trim()).sort());if(seen.has(fingerprint))throw Error(`Question ${i+1} repeats an earlier question`);seen.add(fingerprint);
 return {question,options,correct,explanation,subject,topic,subtopic:String(value("subtopic")||""),difficulty:String(value("difficulty")||"Moderate"),...(value("positive","positivemarks")!==undefined?{positive:Number(value("positive","positivemarks"))}:{}),...(value("negative","negativemarks")!==undefined?{negative:Number(value("negative","negativemarks"))}:{})} as Omit<MockQuestion,"id">;
 });
}
